// Auto-generated list of CSE symbols (code + company name)
// Exposed as a global for easy use in index.html
window.CSE_SYMBOLS = [
  { code: "AAF.N0000", name: "Asia Asset Finance PLC" },
  { code: "AAIC.N0000", name: "Softlogic Life Insurance PLC" },
  { code: "ABAN.N0000", name: "Abans Electricals PLC" },
  { code: "ABL.N0000", name: "Amãna Bank PLC" },
  { code: "ACAP.N0000", name: "Asia Capital PLC" },
  { code: "ACL.N0000", name: "ACL Cables PLC" },
  { code: "ACME.N0000", name: "ACME Printing and Packaging PLC" },
  { code: "AEL.N0000", name: "Access Engineering PLC" },
  { code: "AFS.N0000", name: "Alpha Fire Services PLC" },
  { code: "AFSL.N0000", name: "Abans Finance PLC" },
  { code: "AGAL.N0000", name: "Agalawatte Plantations PLC" },
  { code: "AGST.N0000", name: "AgStar PLC" },
  { code: "AHPL.N0000", name: "Asian Hotels and Properties PLC" },
  { code: "AHUN.N0000", name: "Aitken Spence Hotel Holdings PLC" },
  { code: "AINS.N0000", name: "Arpico Insurance PLC" },
  { code: "ALLI.N0000", name: "Alliance Finance Company PLC" },
  { code: "ALUM.N0000", name: "Alumex PLC" },
  { code: "AMF.N0000", name: "Associated Motor Finance Company PLC" },
  { code: "AMSL.N0000", name: "Asiri Surgical Hospital PLC" },
  { code: "APLA.N0000", name: "ACL Plastics PLC" },
  { code: "ASCO.N0000", name: "Lanka Realty Investments PLC" },
  { code: "ASHO.N0000", name: "Lanka Ashok Leyland PLC" },
  { code: "ASIR.N0000", name: "Asiri Hospital Holdings PLC" },
  { code: "ASIY.N0000", name: "Asia Siyaka Commodities PLC" },
  { code: "ASPH.N0000", name: "Industrial Asphalts (Ceylon) PLC" },
  { code: "ATL.N0000", name: "Amãna Takaful PLC" },
  { code: "ATLL.N0000", name: "Amãna Takaful Life PLC" },
  { code: "AUTO.N0000", name: "The Autodrome PLC" },
  { code: "BALA.N0000", name: "Balangoda Plantations PLC" },
  { code: "BBH.N0000", name: "Browns Beach Hotels PLC" },
  { code: "BERU.N0000", name: "Beruwala Resorts PLC" },
  { code: "BFL.N0000", name: "Bairaha Farms PLC" },
  { code: "BFN.N0000", name: "JANASHAKTHI FINANCE PLC" },
  { code: "BIL.N0000", name: "Browns Investments PLC" },
  { code: "BLUE.N0000", name: "Blue Diamonds Jewellery Worldwide PLC" },
  { code: "BOGA.N0000", name: "Bogala Graphite Lanka PLC" },
  { code: "BOPL.N0000", name: "Bogawantalawa Tea Estates PLC" },
  { code: "BPPL.N0000", name: "BPPL Holdings PLC" },
  { code: "BREW.N0000", name: "Ceylon Beverage Holdings PLC" },
  { code: "BRR.N0000", name: "Bansei Royal Resorts Hikkaduwa PLC" },
  { code: "BRWN.N0000", name: "Brown and Company PLC" },
  { code: "BUKI.N0000", name: "Bukit Darah PLC" },
  { code: "CABO.N0000", name: "Cargo Boat Development Company PLC" },
  { code: "CALF.N0000", name: "Dialog Finance PLC" },
  { code: "CALT.N0000", name: "Capital Alliance PLC" },
  { code: "CARE.N0000", name: "Printcare PLC" },
  { code: "CARG.N0000", name: "Cargills (Ceylon) PLC" },
  { code: "CARS.N0000", name: "Carson Cumberbatch PLC" },
  { code: "CCS.N0000", name: "Ceylon Cold Stores PLC" },
  { code: "CDB.N0000", name: "Citizens Development Business Finance PLC" },
  { code: "CERA.N0000", name: "Lanka Ceramic PLC" },
  { code: "CFI.N0000", name: "Colombo Fort Investments PLC" },
  { code: "CFIN.N0000", name: "Central Finance Company PLC" },
  { code: "CFLB.N0000", name: "The Colombo Fort Land & Building PLC" },
  { code: "CFVF.N0000", name: "First Capital Holdings PLC" },
  { code: "CHL.N0000", name: "Ceylon Hospitals PLC" },
  { code: "CHMX.N0000", name: "Chemanex PLC" },
  { code: "CHOT.N0000", name: "Ceylon Hotels Corporation PLC" },
  { code: "CIC.N0000", name: "CIC Holdings PLC" },
  { code: "CIND.N0000", name: "Central Industries PLC" },
  { code: "CINS.N0000", name: "Ceylinco Holdings PLC" },
  { code: "CINV.N0000", name: "Ceylon Investment PLC" },
  { code: "CIT.N0000", name: "Colombo Investment Trust PLC" },
  { code: "CITH.N0000", name: "Hikkaduwa Beach Resort PLC" },
  { code: "CITW.N0000", name: "Waskaduwa Beach Resort PLC" },
  { code: "CLND.N0000", name: "Colombo Land and Development Company PLC" },
  { code: "COCO.N0000", name: "Renuka Foods PLC" },
  { code: "COCR.N0000", name: "Commercial Credit and Finance PLC" },
  { code: "COLO.N0000", name: "C M Holdings PLC" },
  { code: "COMB.N0000", name: "Commercial Bank of Ceylon PLC" },
  { code: "COMD.N0000", name: "Commercial Development Company PLC" },
  { code: "CONN.N0000", name: "Hayleys Leisure PLC" },
  { code: "COOP.N0000", name: "Co-operative Insurance Company PLC" },
  { code: "CPRT.N0000", name: "Kerner Haus Global Solutions PLC" },
  { code: "CRL.N0000", name: "Softlogic Finance PLC" },
  { code: "CSD.N0000", name: "Seylan Developments PLC" },
  { code: "CSF.N0000", name: "Nation Lanka Finance PLC" },
  { code: "CTBL.N0000", name: "Ceylon Tea Brokers PLC" },
  { code: "CTC.N0000", name: "Ceylon Tobacco Company PLC" },
  { code: "CTEA.N0000", name: "Dilmah Ceylon Tea Company PLC" },
  { code: "CTHR.N0000", name: "C T Holdings PLC" },
  { code: "CTLD.N0000", name: "CT Land Development PLC" },
  { code: "CWL.N0000", name: "Chrissworld PLC" },
  { code: "CWM.N0000", name: "C. W. Mackie PLC" },
  { code: "DFCC.N0000", name: "DFCC Bank PLC" },
  { code: "DIAL.N0000", name: "Dialog Axiata PLC" },
  { code: "DIMO.N0000", name: "Diesel & Motor Engineering PLC" },
  { code: "DIPD.N0000", name: "Dipped Products PLC" },
  { code: "DIST.N0000", name: "Distilleries Company of Sri Lanka PLC" },
  { code: "DOCK.N0000", name: "Colombo Dockyard PLC" },
  { code: "DPL.N0000", name: "Dankotuwa Porcelain PLC" },
  { code: "EAST.N0000", name: "East West Properties PLC" },
  { code: "EBCR.N0000", name: "E.B. Creasy & Company PLC" },
  { code: "ECL.N0000", name: "eChannelling PLC" },
  { code: "EDEN.N0000", name: "Eden Hotel Lanka PLC" },
  { code: "ELPL.N0000", name: "Elpitiya Plantations PLC" },
  { code: "EMER.N0000", name: "Eastern Merchants PLC" },
  { code: "EML.N0000", name: "EML Consultants PLC" },
  { code: "ETWO.N0000", name: "Equity Two PLC" },
  { code: "EXT.N0000", name: "Exterminators Plc" },
  { code: "FCT.N0000", name: "First Capital Treasuries PLC" },
  { code: "GEST.N0000", name: "Gestetner of Ceylon PLC" },
  { code: "GHLL.N0000", name: "GALADARI Hotels (Lanka) PLC" },
  { code: "GLAS.N0000", name: "PGP Glass Ceylon PLC" },
  { code: "GRAN.N0000", name: "Ceylon Grain Elevators PLC" },
  { code: "GREG.N0000", name: "Ambeon Holdings PLC" },
  { code: "GUAR.N0000", name: "Ceylon Guardian Investment Trust PLC" },
  { code: "HAPU.N0000", name: "Hapugastenne Plantations PLC" },
  { code: "HARI.N0000", name: "Harischandra Mills PLC" },
  { code: "HASU.N0000", name: "HNB Assurance PLC" },
  { code: "HAYC.N0000", name: "Haycarb PLC" },
  { code: "HAYL.N0000", name: "Hayleys PLC" },
  { code: "HBS.N0000", name: "hSenid Business Solutions PLC" },
  { code: "HDFC.N0000", name: "Housing Development Finance Corporation Bank of Sri Lanka" },
  { code: "HELA.N0000", name: "Hela Apparel Holdings PLC" },
  { code: "HEXP.N0000", name: "Hayleys Fibre PLC" },
  { code: "HHL.N0000", name: "Hemas Holdings PLC" },
  { code: "HNB.N0000", name: "Hatton National Bank PLC" },
  { code: "HNBF.N0000", name: "HNB Finance PLC" },
  { code: "HOPL.N0000", name: "Horana Plantations PLC" },
  { code: "HPFL.N0000", name: "Lotus Hydro Power PLC" },
  { code: "HPL.N0000", name: "Hatton Plantations PLC" },
  { code: "HPWR.N0000", name: "Resus Energy PLC" },
  { code: "HSIG.N0000", name: "Hotel Sigiriya PLC" },
  { code: "HUNA.N0000", name: "Hunas Holdings PLC" },
  { code: "HUNT.N0000", name: "Hunter & Company PLC" },
  { code: "HVA.N0000", name: "HVA Foods PLC" },
  { code: "IDL.N0000", name: "Serendib Engineering Group PLC" },
  { code: "JAT.N0000", name: "JAT Holdings PLC" },
  { code: "JETS.N0000", name: "Jetwing Symphony PLC" },
  { code: "JINS.N0000", name: "Janashakthi Insurance PLC" },
  { code: "JKH.N0000", name: "John Keells Holdings PLC" },
  { code: "JKL.N0000", name: "John Keells PLC" },
  { code: "KAHA.N0000", name: "Kahawatte Plantations PLC" },
  { code: "KCAB.N0000", name: "Kelani Cables PLC" },
  { code: "KDL.N0000", name: "Kelsey Developments PLC" },
  { code: "KFP.N0000", name: "Keells Food Products PLC" },
  { code: "KGAL.N0000", name: "Kegalle Plantations PLC" },
  { code: "KHC.N0000", name: "The Kandy Hotels Co. (1938) PLC" },
  { code: "KOTA.N0000", name: "Kotagala Plantations PLC" },
  { code: "KPHL.N0000", name: "Kapruka Holdings PLC" },
  { code: "KVAL.N0000", name: "Kelani Valley Plantations PLC" },
  { code: "KZOO.N0000", name: "Ceylon Land & Equity PLC" },
  { code: "LALU.N0000", name: "Lanka Aluminium Industries PLC" },
  { code: "LAMB.N0000", name: "Kotmale Holdings PLC" },
  { code: "LCBF.N0000", name: "Lanka Credit and Business Finance PLC" },
  { code: "LCEY.N0000", name: "Lankem Ceylon PLC" },
  { code: "LDEV.N0000", name: "Lankem Developments PLC" },
  { code: "LFIN.N0000", name: "LB Finance PLC" },
  { code: "LGIL.N0000", name: "LOLC General Insurance PLC" },
  { code: "LGL.N0000", name: "LAUGFS Gas PLC" },
  { code: "LHCL.N0000", name: "The Lanka Hospitals Corporation PLC" },
  { code: "LHL.N0000", name: "The Lighthouse Hotel PLC" },
  { code: "LIOC.N0000", name: "Lanka IOC PLC" },
  { code: "LION.N0000", name: "Lion Brewery (Ceylon) PLC" },
  { code: "LITE.N0000", name: "Laxapana PLC" },
  { code: "LLUB.N0000", name: "Chevron Lubricants Lanka PLC" },
  { code: "LMF.N0000", name: "Lanka Milk Foods (CWE) PLC" },
  { code: "LOFC.N0000", name: "LOLC Finance PLC" },
  { code: "LOLC.N0000", name: "LOLC Holdings PLC" },
  { code: "LPL.N0000", name: "LAUGFS Power PLC" },
  { code: "LPRT.N0000", name: "Lake House Printers and Publishers PLC" },
  { code: "LUMX.N0000", name: "Luminex Plc" },
  { code: "LVEF.N0000", name: "LVL Energy Fund PLC" },
  { code: "LVEN.N0000", name: "Lanka Ventures PLC" },
  { code: "LWL.N0000", name: "Lanka Walltiles PLC" },
  { code: "MADU.N0000", name: "Madulsima Plantations PLC" },
  { code: "MAL.N0000", name: "Malwatte Valley Plantations PLC" },
  { code: "MARA.N0000", name: "Marawila Resorts PLC" },
  { code: "MASK.N0000", name: "Maskeliya Plantations PLC" },
  { code: "MBSL.N0000", name: "Merchant Bank of Sri Lanka & Finance PLC" },
  { code: "MCPL.N0000", name: "Mahaweli Coconut Plantations PLC" },
  { code: "MEL.N0000", name: "Greentech Energy PLC" },
  { code: "MELS.N0000", name: "Melstacorp PLC" },
  { code: "MGT.N0000", name: "Hayleys Fabric PLC" },
  { code: "MHDL.N0000", name: "Millennium Housing Developers PLC" },
  { code: "MRH.N0000", name: "Mahaweli Reach Hotels PLC" },
  { code: "MSL.N0000", name: "Mercantile Shipping Company PLC" },
  { code: "MULL.N0000", name: "Muller & Phipps (Ceylon) PLC" },
  { code: "NAMU.N0000", name: "Namunukula Plantations PLC" },
  { code: "NDB.N0000", name: "National Development Bank PLC" },
  { code: "NEH.N0000", name: "The Nuwara Eliya Hotels Company PLC" },
  { code: "NHL.N0000", name: "Nawaloka Hospitals PLC" },
  { code: "NTB.N0000", name: "Nations Trust Bank PLC" },
  { code: "ODEL.N0000", name: "Odel PLC" },
  { code: "OFEQ.N0000", name: "Office Equipment PLC" },
  { code: "ONAL.N0000", name: "On'ally Holdings PLC" },
  { code: "OSEA.N0000", name: "Overseas Realty (Ceylon) PLC" },
  { code: "PABC.N0000", name: "Pan Asia Banking Corporation PLC" },
  { code: "PACK.N0000", name: "Ex-pack Corrugated Cartons PLC" },
  { code: "PALM.N0000", name: "Palm Garden Hotels PLC" },
  { code: "PAP.N0000", name: "Panasian Power PLC" },
  { code: "PARA.N0000", name: "Paragon Ceylon PLC" },
  { code: "PARQ.N0000", name: "Swisstek (Ceylon) PLC" },
  { code: "PEG.N0000", name: "Pegasus Hotels of Ceylon PLC" },
  { code: "PHAR.N0000", name: "Colombo City Holdings PLC" },
  { code: "PINS.N0000", name: "People's Insurance PLC" },
  { code: "PLC.N0000", name: "People's Leasing & Finance PLC" },
  { code: "PLR.N0000", name: "Prime Lands Residencies PLC" },
  { code: "PMB.N0000", name: "PMF Finance PLC" },
  { code: "RAL.N0000", name: "Renuka Agri Foods PLC" },
  { code: "RCH.N0000", name: "Renuka Hotels PLC" },
  { code: "RCL.N0000", name: "Royal Ceramics Lanka PLC" },
  { code: "REEF.N0000", name: "Citrus Leisure PLC" },
  { code: "RENU.N0000", name: "Renuka City Hotels PLC" },
  { code: "REXP.N0000", name: "Richard Pieris Exports PLC" },
  { code: "RFL.N0000", name: "Ramboda Falls PLC" },
  { code: "RGEM.N0000", name: "Radiant Gems International PLC" },
  { code: "RHL.N0000", name: "Renuka Holdings PLC" },
  { code: "RHTL.N0000", name: "The Fortress Resorts PLC" },
  { code: "RICH.N0000", name: "Richard Pieris and Company PLC" },
  { code: "RIL.N0000", name: "R I L Property PLC" },
  { code: "RPBH.N0000", name: "Royal Palms Beach Hotels PLC" },
  { code: "RWSL.N0000", name: "Raigam Wayamba Salterns PLC" },
  { code: "SAMP.N0000", name: "Sampath Bank PLC" },
  { code: "SCAP.N0000", name: "Softlogic Capital PLC" },
  { code: "SDB.N0000", name: "SANASA Development Bank PLC" },
  { code: "SDF.N0000", name: "Sarvodaya Development Finance PLC" },
  { code: "SEMB.N0000", name: "SMB Finance PLC" },
  { code: "SERV.N0000", name: "The Kingsbury PLC" },
  { code: "SEYB.N0000", name: "Seylan Bank PLC" },
  { code: "SFCL.N0000", name: "Senkadagala Finance PLC" },
  { code: "SFIN.N0000", name: "Singer Finance (Lanka) PLC" },
  { code: "SHAW.N0000", name: "Lee Hedges PLC" },
  { code: "SHL.N0000", name: "Softlogic Holdings PLC" },
  { code: "SHOT.N0000", name: "Serendib Hotels PLC" },
  { code: "SIGV.N0000", name: "Sigiriya Village Hotels PLC" },
  { code: "SIL.N0000", name: "Samson International PLC" },
  { code: "SING.N0000", name: "Standard Capital PLC" },
  { code: "SINH.N0000", name: "Singhe Hospitals PLC" },
  { code: "SINS.N0000", name: "Singer (Sri Lanka) PLC" },
  { code: "SIRA.N0000", name: "Sierra Cables PLC" },
  { code: "SLND.N0000", name: "Serendib Land PLC" },
  { code: "SLTL.N0000", name: "Sri Lanka Telecom PLC" },
  { code: "SMOT.N0000", name: "Sathosa Motors PLC" },
  { code: "SPEN.N0000", name: "Aitken Spence PLC" },
  { code: "STAF.N0000", name: "Dolphin Hotels PLC" },
  { code: "SUN.N0000", name: "Sunshine Holdings PLC" },
  { code: "SWAD.N0000", name: "The Swadeshi Industrial Works PLC" },
  { code: "TAFL.N0000", name: "Three Acre Farms PLC" },
  { code: "TAJ.N0000", name: "TAL Lanka Hotels PLC" },
  { code: "TANG.N0000", name: "Tangerine Beach Hotels PLC" },
  { code: "TAP.N0000", name: "Ambeon Capital PLC" },
  { code: "TESS.N0000", name: "Tess Agro PLC" },
  { code: "TILE.N0000", name: "Lanka Tiles PLC" },
  { code: "TJL.N0000", name: "Teejay Lanka PLC" },
  { code: "TKYO.N0000", name: "Tokyo Cement Company (Lanka) PLC" },
  { code: "TPL.N0000", name: "Talawakelle Tea Estates PLC" },
  { code: "TRAN.N0000", name: "Trans Asia Hotels PLC" },
  { code: "TSML.N0000", name: "Tea Smallholder Factories PLC" },
  { code: "TYRE.N0000", name: "Kelani Tyres PLC" },
  { code: "UAL.N0000", name: "Union Assurance PLC" },
  { code: "UBC.N0000", name: "Union Bank of Colombo PLC" },
  { code: "UCAR.N0000", name: "Union Chemicals Lanka PLC" },
  { code: "UDPL.N0000", name: "Udapussellawa Plantations PLC" },
  { code: "UML.N0000", name: "United Motors Lanka PLC" },
  { code: "VFIN.N0000", name: "Vallibel Finance PLC" },
  { code: "VLL.N0000", name: "Vidullanka PLC" },
  { code: "VONE.N0000", name: "Vallibel One PLC" },
  { code: "VPEL.N0000", name: "Vallibel Power Erathna PLC" },
  { code: "WAPO.N0000", name: "Galle Face Capital Partners PLC" },
  { code: "WATA.N0000", name: "Watawala Plantations PLC" },
  { code: "WIND.N0000", name: "WindForce PLC" },
  { code: "AGPL.N0000", name: "Agarapatana Plantations Limited" },
  { code: "CSLK.N0000", name: "Cable Solutions PLC" },
  { code: "CBNK.N0000", name: "Cargills Bank PLC" },
  { code: "SOY.N0000", name: "Convenience Foods (Lanka) PLC" },
  { code: "PKME.N0000", name: "Digital Mobility Solutions Lanka PLC" },
  { code: "KHL.N0000", name: "John Keells Hotels PLC" },
  { code: "MFPE.N0000", name: "Maharaja Foods PLC" },
  { code: "MERC.N0000", name: "Mercantile Investments and Finance PLC" },
  { code: "MDL.N0000", name: "Myland Developments PLC" },
  { code: "UBF.N0000", name: "UB Finance PLC" },
  { code: "YORK.N0000", name: "York Arcade Holdings PLC" },
  { code: "CALH.N0000", name: "Capital Alliance Holdings Limited" },
  { code: "TKYO.X0000", name: "Tokyo Cement (Non Voting)" }
];
